### ISSUE TITLE
web版

### ISSUE THREAD

**Issue by yegetables** [SSmJaE/XueXiTonsSign_Electron#10]
可以开发个web版吗,方便部署在vps上,vps上没有图形环境

**Comment by SSmJaE** [comment]
有考虑实现 油猴 + 命令行 + GUI 三合一，毕竟核心逻辑都是一样的，只是交互方式不太一样
油猴版(通过脚本猫，scriptcat)，是否符合你对“web版”的预期呢？
如果部署在vps上的，可能命令行更合适吧

**Comment by yegetables** [comment]
之前想的web版是通过在vps的搭建的web网站来操作vps,管理实现学习通课程和监控运行状况
油猴可能并不适合这样做 ,我想命令行可能更适合吧,
核心是为了睡觉的时候不开电脑,远程vps云服务器自动实现签到,达到解偶效果.
vue项目还是很容易做成web的
感谢开发者

**Comment by clansty** [comment]
https://github.com/Clansty/superstar-checkin 纯命令行的版本

**Comment by SSmJaE** [comment]
你的意思是前后端分离吧，后端运行签到服务， 前端作为控制面板，前后端之间通信？
如果分为前后端的话，可以实现，不过可能要等一阵子，最近比较忙

**Comment by yegetables** [comment]
是的,是这个意思,
